gpu_num : 0
seed : 111
test_dir : "/data/ephemeral/home/dataset"
annotation_dir : "/data/ephemeral/home/dataset/test.json"
train_serial : "20240103_121446"


#data
# input_size: [480,256]
# resize_size: [128, 96]
# scaler: clahe
transform: testTransform
num_workers: 12
batch_size : 64