gpu_num : 0
seed : 111
train_dir : "/data/ephemeral/home/dataset"
annotation_dir : "/data/ephemeral/home/dataset/train.json"

#wandb
wandb : True
wandb_project: "CV06-OD"
wandb_run : "yolov1resnetd"
wandb_note : wandb_note


# Train / val
val_size: 0.2

#data
dataset: BaseDataset
# input_size: [480,256]
# centor_crop : [256,256]
# resize_size: [224, 224]
# scaler: clahe
transform: baseTransform
num_workers: 12
shuffle: True
drop_last: False
batch_size : 16
# mean : [0.485, 0.456, 0.406]
# std : [0.229, 0.224, 0.225]

#Model
model_custom : True
multi_label : False
model:
  architecture : YoloV1ResNet50d
  args:
    split_size : 7
    num_boxes : 2
    num_classes : 10
loss:
  name: YoloV1Loss #Cross_entropy #FocalLoss # MeanCCELoss
  args:
    S: 7
    B: 2
    C: 10

metrics: 
  - mean_ap

optimizer:
  name: Adam
  args:
    lr: 2.0e-05
    weight_decay: 0.0
scheduler:
  name: MultiStepLR
  args:
    milestones: [40, 70]
    gamma: 0.1

#train
n_epochs: 100
early_stopping_count : 10