gpu_num : 0
seed : 666
train_dir : "/data/ephemeral/home/dataset/"
train_annotation_dir : "/data/ephemeral/home/dataset/new_train.json"
val_annotation_dir : "/data/ephemeral/home/dataset/new_val.json"

#wandb
wandb : True
wandb_project: "CV06-OD"
wandb_entity: "innovation-vision-tech"
wandb_run : "detr_r50"
wandb_note : wandb_note


classes: ["General trash", "Paper", "Paper pack", "Metal", "Glass", "Plastic", "Styrofoam", "Plastic bag", "Battery", "Clothing"]

custom_batch_size: True
samples_per_gpu: 8
workers_per_gpu: 4


py_path: "cv06/my_deformable_detr_r50_16x2_50e_coco.py"
# mmdetection/configs 안의 경로

custom_py: False
# mmdetection/configs에 custom 설정 파일을 만든 경우 custom_py를 True로 변경

# cfg 변경할 옵션들을 여기에 입력
# custom_py: True인 경우 사용되지 않음
cfg_options:
  model.roi_head.bbox_head.num_classes: 10
  evaluation.interval: 1
  evaluation.metric: "bbox"
  evaluation.save_best: "bbox_mAP"
  checkpoint_config.max_keep_ckpts: 3
  checkpoint_config.interval: 1
  default_hooks.early_stopping:
    type: "EarlyStoppingHook"
    monitor: "coco/bbox_mAP"
    patience: 6
    min_delta: 0.005
